# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05a7229713d15ded778acc3063d5972ef613345aa43526ea47efbc12635147ca67bae320fa3e6e139209b29e070ea35fd80a09058f79ed47a6f11d5e6c41efa4

test:
  secret_key_base: 74cd842f8ea9ebf95367455baba970616deb3edfa3d8234c1af582278db069069a6b3a8be2731064dc9c428859ede7705025da864ccee0feb812f5aa6f8cea2a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
